from modules.langchain_assistant.langchain_productivy_assistant import LangChainProductivityAssistant
from modules.langchain_assistant.langchain_browser_assistant import LangChainBrowserAssistant
from modules.langchain_assistant.langchain_scientist_assistant import LangChainScientisAssistant
from modules.langchain_assistant.langchain_chat_assistant import LangChainChatAssistant
from modules.langchain_assistant.langchain_document_assistant import LangChainDocumentAssistant
from modules.langchain_assistant.langchain_image_assistant import LangchainImageAssistant